---
title: "R Notebook"
output: html_notebook
---

```{r}
library(EBSeq)
library(igraph)
library(stringr)
library(foreach)
library(doParallel)
```

```{r}
genes_network <- read.csv("~/UW_classes/BMI826/project/data/protein_interactions.txt",sep = "\t",stringsAsFactors = FALSE, header = FALSE)

genes_network <- genes_network[,c('V2','V5','V6','V15')]
names(genes_network) <- c("species",'protein1','protein2','score')

str_split <- function(s,sep='-'){
  splits <- strsplit(s,sep)[[1]]
  if(length(splits) >= 2)
    return(splits[2])
  else
    return(s)
}

genes_network$species <- sapply(genes_network$species, function(x) str_split(x,'_'))
genes_network$protein1 <- sapply(genes_network$protein1, function(x) str_split(x,':'))
genes_network$protein2 <- sapply(genes_network$protein2, function(x) str_split(x,':'))
genes_network$score <- sapply(genes_network$score, function(x) str_split(x,':'))
genes_network$score <- as.numeric(genes_network$score)


genes_network <- genes_network[genes_network$species == 'HUMAN',c("protein1","protein2","score")]

tail(genes_network)
```


Storing the clean data
```{r}
#write.csv(genes_network,file = "~/UW_classes/BMI826/project/data/gene_network_clean.csv", row.names = FALSE, quote = FALSE)
```


```{r}
hist(genes_network$score, breaks = 100)
```

```{r}
protein.graph <- graph.data.frame(genes_network,directed = FALSE)
vcount(protein.graph)
```





## More statastics about the skeliton graph

```{r}
ns <- neighbors(protein.graph,'P85B')
ends(protein.graph,'GNB5')
```




```{r}
lungbrain_data <- read.csv("~/UW_classes/BMI826/project/data/lungbrain_data_normed.csv", stringsAsFactors = FALSE)

row.names(lungbrain_data) <- lungbrain_data[,1]
lungbrain_data <- lungbrain_data[,2:dim(lungbrain_data)[2]]

head(lungbrain_data)
```


```{r}
conditions <- sapply(names(lungbrain_data), function(x) str_sub(x,-2,-1))
lt_bt <- conditions == 'LT' |  conditions == 'BT'

data_lt_bt <- lungbrain_data[,lt_bt]

EBOut <- EBTest(Data=as.matrix(data_lt_bt), Conditions=conditions[lt_bt], sizeFactors=rep(1,dim(data_lt_bt)[2]), maxround=5)


EBDERes = GetDEResults(EBOut, FDR=0.05)

p_values <- EBOut$PPDE

```


# Cleaning the network (removing the nodes not present in the RNA sequencing data)
```{r}
genes_common <- intersect(genes_network$protein1,names(p_values))
G1 <- induced_subgraph(protein.graph,genes_common, impl ="auto")
p_values <- p_values[genes_common]

```


```{r}
p_mean <- mean(p_values)
p_sd <- sd(p_values)
z_scores <- (p_values-p_mean)/p_sd

#z_scores <- abs(z_scores)
```

## Pre-building Mu_k and Sigma_k using Monte-Carlo simulation
# Mu_k : Mean z-scores for k randonly selected nodes
# Sigma_k : Standard Deviation of z-scores for k randonly selected nodes


```{r}

no_cores <- detectCores() - 1
cl <- makeCluster(no_cores)
registerDoParallel(no_cores)

max_k <- length(z_scores)

combine <- function(x, ...) {  
  mapply(rbind, x, ..., SIMPLIFY = FALSE)
}

mc_results <- foreach(k=1:max_k, .export = "z_scores",.combine = combine, .multicombine = TRUE) %dopar%{
  sim_count = 100
  mc_z <- numeric(sim_count)
  for(i in 1:sim_count){
    mc_z[i] <- sum(sample(z_scores,size = k,replace = TRUE))/sqrt(k)
  }
  mu_k <- mean(mc_z)
  sigma_k <- sd(mc_z)
  list(mu_k,sigma_k)
}

stopImplicitCluster()

mu_k <- mc_results[[1]]
sigma_k <- mc_results[[2]]
```



## Subnetwork Scoring
```{r}
score_subgrpup <- function(group_genes){
  #getting the z-score for the genes
  k <- length(group_genes)
  z_A = sum(group_genes)/k**(3/4)
  
  s_A <- (z_A - mu_k[k])/sigma_k[k]
  return(s_A)
}
```

```{r}

simulated_annealing <- function(G,N,d=100,score_func,Temp_high,cool){
  nodes <- names(V(G))
  nodes_count <- length(nodes)
  #print('nodes_count')
  #print(nodes_count)
  nodes_active <- 1* (runif(nodes_count) >= 0.5)
  #print('nodes_active')
  #print(nodes_active)
  subnet_score <- score_func(z_scores[nodes_active == 1])
  #print('subnet_score')
  #print(subnet_score)
  temperature <- Temp_high
  
  blocked_list <- c()
  
  track_scores = numeric(N)
  track_temp_p = numeric(N)
  track_active_nodes = numeric(N)
  for(count in 1:N){
    if(temperature > 0.001){
      
      node_selected <- sample(1:nodes_count,1)
      #print('node_selected')
      #print(node_selected)
      #node_name = nodes[node_selected]
      
      while(node_selected %in% blocked_list){
        node_selected <- sample(1:nodes_count,1)
      }
      
      changed_state <- nodes_active
      changed_state[node_selected] <- 1* (!changed_state[node_selected])#fliping the node state
      
      changed_subnet_score <- score_func(z_scores[changed_state == 1])
      #print('changed_subnet_score')
      #print(changed_subnet_score)
      
      p <- exp((changed_subnet_score-subnet_score)/temperature)
      track_temp_p[count] <- p
      if((changed_subnet_score > subnet_score) | (runif(1) < p)){
        nodes_active <- changed_state
        subnet_score <- changed_subnet_score
        
        if(degree(G,node_selected) >= d){
          #put the connected noded in the blocked list
          connected_nodes <- names(neighbors(G,names(z_scores[node_selected])))
          connected_idx <- which(names(z_scores) %in% connected_nodes)
          connected_idx<-  connected_idx[! connected_idx %in% which(nodes_active == 1)]
          blocked_list <- c(blocked_list,connected_idx)
        }
        
      }
      
      track_scores[count] <- subnet_score
      track_active_nodes[count] <- sum(nodes_active)
      #what's the new temperature
      temperature <- temperature * cool
      }else{
        print(paste("steps executed : ",count))
        print(paste("quenched at tempeature : ",temperature))
        
        break()
      }
    if(count %% 100 ==0){
      cat(".")
    }
  }
  return(list(nodes_active,track_scores,track_temp_p,track_active_nodes))
}

```


```{r}

result <- simulated_annealing(G1,100000,100,score_subgrpup,100000,.999)
```


## Ploting


```{r}
p_sorted <- sort(p_values)


cat(paste(names(p_sorted[p_sorted < 0.005]),'\n'))

cat(paste(names(z_scores)[result[[1]] == 1],'\n'))


```








```{r}
plot(1:18413,result[[2]][1:18413], 'l')





k_counts <- seq(1,length(z_scores))
mu_k_score <- (mu_k)/(k_counts)**(1/2)
plot(1:length(mu_k),mu_k_score, 'l')

```








## testing
```{r}
c  = 0.99
c_list = numeric(1000)
c_list[1] = 1
for(i in 2:1000){
  c_list[i] <- c_list[i-1]*c
}

plot(1:1000,c_list)



##########
plot(1:length(sigma_k),sigma_k,'l')

######
length(V(G1)) == length(z_scores)

```

